### ISSUE TITLE
区块链区块链

### ISSUE THREAD

**Issue by Alkaid-Benetnash** [zzh1996/distributed-file-storage#1]
# 有什么想法快在下面评论，比较棘手的问题另开issue讨论
#### 说明记号

`我想到了，还不确定`

**觉得需要花点精力好好设计**
### 块的结构

| 项 | 说明 |
| :-- | :-- |
| Public Key : PK | 用keyid或fingerprint(偏向用这个) |
| Parent: sha256(last block) | 区块链的链 |
| `Parent of the same PK` | `我觉得应该记录一下同一个公钥上一次提交对应的block` |
| payload hash | 区块附加部分的校验，整个附加信息生成一个校验（Merkle） |
| Root directory hash | 用随机生成的对称密钥加密过的根目录hash，让其他人看不到我的根是什么 |
| 公钥加密过的 Root directory 对称密钥 | 把对称密钥保护起来，用我自己的私钥可以解开，进而获得对称密钥，得到根的hash |
| signature of entries above | 给别人证实上面这一大块，真的是本人生成的 |

| 可能的附加信息 | 说明 |
| :-- | :-- |
| 本次提交删除的内容 | 以文件/目录在后面存储的hash为单位，目的是方便从后面彻底删除某些文件。比如可以设置距离最新的区块10块远之后，这部分记载的hash告诉给后面的chord可以把这些东西彻底删除了。 |
#### 背景

后面chord实现的p2p网络是一个环，让xuqiang组提供和环上附近节点（比如附近8个）通信的接口。
以下加粗的是可能需要重点考虑的逻辑
#### 新创建一个节点

通过chord连接附近节点，发送同步区块链的请求。从所有的回复中**挑选**哪些区块从哪些peer同步。
#### 已经创建过的节点启动

和新创建的节点相比，已经存在的节点`是不是应该同步时标注自己的public key，有助于别的节点不会发送其它PK的区块的附加内容，如上述的删除记录`
#### 正在使用时区块链有更新

当本节点提交了一个区块后，推送更改给临近的节点。
临近的节点收到推送后，先校验签名，再查看是不是与自己已有的区块不冲突，冲突（`可能有的不是最新的区块链`）的话返回一个拒绝推送，导致进行推送的节点重新去申请同步区块链。如果推送被接受了，那么就递归推送给附近节点，递归终点是已有这一块或者这一块无效（签名无效、区块链产生了分支）
如果收到的推送和当前用户的PK不同，那么直接同步下来新区块即可，如果是自身的PK，那么除了同步区块，还应该更新本地缓存的文件系统索引（storage.db）。`那么问题来了，如果此时storage.db已经有了一些新更改了怎么办。。。`

**Comment by siblingtattoo** [comment]
一个区块链类应包含的内容：
database(√)
区块链高度(√)
本地的公钥(√)
本地最高块的hash(√)
(暂定)

注意：区块block结构中加上了高度，也需要其他节点来验证。这样区块链中的高度都是可信的
注意：在更新区块时，本地不能提交
1. 请求查询：  A节点广播自己区块链高度和最高块的hash值，请求响应
2. 响应查询：  B节点收到其他节点(A节点)请求查询的消息后，如果A的高度小于B的区块链高度，并且A发来的hash值不在本地区块中，说明A的区块链是分叉的，并且是短的那一条，B回复给A消息说：“你分叉了”；如果A的高度大于B的区块链高度并且A发来的hash也不在B的区块链中，则说明B分叉了，并且是短的那一条，这时B要请求查询，更新自己的短链；如果A、B一样高，则不做操作；如果A短于B，并且A发来的hash在B的区块链中，B要有顺序的发送一串hashes，第一个hash的parent是A发来的parent，最后一个hash是B的最高块的hash
3. 请求同步：  如果A收到B说“你分叉了”，它要将最高块回退一个块，把原来的最高块舍去(如果是它自己提交的区块，打回暂存区；如果不是自己提交的，就直接删除)，然后再请求查询；如果A收到了B发的一串hashes，它要检查自己的buffer里有没有区块有相同的hash，如果有，就不再需要下载该区块了，如果没有，A选能发来最长链的节点传给它自己想要哪些块的hash
4. 响应同步：  收到请求同步的信息后，暂存下它希望自己传输的块的hash值，一个一个发回给标识的节点A
5. 更新区块：  本地B节点验证广播来的区块.先看新块的高度，如果不大于本地最高块，则返回拒绝；如果比本地最高块高1，则继续校验签名；如果不是前两种情况，B要继续校验签名通过后把新块放到暂存区里，然后发送请求查询信号（自己短了，要更新区块）。校验签名后，若新块高度是本地高度加1，且新块parent不是本地最高块，则本地不更新区块，也不发送消息；否则，返回确认推送(?)，并更新自己的区块链；更新完成后，本地才能提交新的区块
6. 本地提交：本地缓存区中的内容一经提交，生成一个区块(_)，parent置为本地的最新区块，并推送出这个新区块，如果收到了一个确认推送的信息，则显示本地提交成功；若收到拒绝信息，本地的缓存区中恢复为被拒绝的区块的提交内容，并自动向周围块请求查询、同步；在同步区块完成后，用户才能选择进行下一次提交
(_): payload和文件系统会在广播推送区块之前，被一起传到xuqiang组
7. 删除文件：每个节点本地会维护一个指针，它指向本地区块链高度减10位置的区块，如果这个区块的public key就是自己本身，并且它的payload_hash(payload的索引hash)不为0，则由此节点负责删除xuqiang组存的文件。具体过程是：先根据payload_hash去下载payload(如果payload_hash对应的位置为空，说明已被删除，不做其他操作)，然后发送payload_hash中存的被删文件hash值给xuqiang组，最后再发payload_hash给他们，负责把payload也删掉
8. 生成一个区块：包括生成根目录hash(对称密钥加密)，sym_key(公钥加密)，signature(对什么的签名?)，涉及到让用户输入自己加密本地公私钥的对称密钥
